language: php

php:
  - 7.0

sudo: required

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update --no-interaction
  - composer global require "hirak/prestissimo:^0.3"
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - nvm install node

install:
  - composer install --no-interaction --prefer-dist
  - composer create-project nette/code-checker tmp/code-checker ~2.5 --no-interaction --prefer-dist
  - npm install -g npm@'>=2.13.0'
  - npm install
  - npm install -g bower
  - npm install -g typings
  - npm install -g grunt
  - gem install sass
  - bower install
  - typings install

before_script:
  - mysql -u root -e 'CREATE DATABASE online_climbing_tests;'

script:
  - ./vendor/bin/tester ./tests -c ./tests/php-travis.ini --setup ./tests/setup.php -p php-cgi -s
  - php tmp/code-checker/src/code-checker.php -d app --short-arrays
  - grunt build:app

cache:
  directories:
  - $HOME/.cache/bower
  - $HOME/.composer
  - $HOME/.npm
  - ./.sass-cache
  - ./.tscache

notifications:
  slack: white-line:ex957N9S9Ud59iBzMIn91uEw
  email: false
