language: php

php:
  - 5.6

before_install:
  - composer self-update --no-interaction

install:
  - composer install --no-interaction --prefer-source
  - composer create-project nette/code-checker tmp/code-checker ~2.5 --no-interaction --prefer-source
  - npm install
  - npm install -g bower
  - npm install -g typings
  - npm install -g grunt
  - gem install sass
  - bower install

before_script:
  - mysql -u root -e 'CREATE DATABASE online_climbing_tests;'
  #- mysql -u root online_climbing < tests/data/testData.sql

script:
#  - php www/index.php migrations:migrate --no-interaction
  - ./vendor/bin/tester ./tests -c ./tests/php-travis.ini --setup ./tests/setup.php -p php-cgi -s
  - php tmp/code-checker/src/code-checker.php --short-arrays
  - grunt build:app

#after_failure:
  # Print *.actual file contents
  #- for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

#addons:
#  artifacts:
#    paths:
#      - ./log
#  s3_region: eu-central-1

notifications:
  slack: online-climbing:lfDdbU5bapiHaU0xyakS14WU
  email: false
