language: php

php:
  - 5.6

before_install:
  - composer self-update --no-interaction

install:
  - composer install --no-interaction --prefer-source
  - composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction

before_script:
  - mysql -u root -e 'CREATE DATABASE online_climbing;'
  #- mysql -u root online_climbing < tests/data/testData.sql

script:
#  - php www/index.php migrations:migrate --no-interaction
  - ./vendor/bin/tester -p php-cgi -s -c ./tests/php-travis.ini ./tests
  - php temp/code-checker/src/code-checker.php --short-arrays

#after_failure:
  # Print *.actual file contents
  #- for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

addons:
  artifacts:
    s3_region: eu-west-1
    paths:
      - ./log

notifications:
  slack: online-climbing:lfDdbU5bapiHaU0xyakS14WU
  email: false
