language: php

php:
  - 5.6

before_install:
  - composer self-update --no-interaction

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE online_climbing;'
  #- mysql -u root online_climbing < tests/data/testData.sql

script:
  - php www/index.php migrations:migrate --no-interaction
  - ./vendor/bin/tester -p php-cgi -s -c ./tests/php-travis.ini ./tests

#after_failure:
  # Print *.actual file contents
  #- for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

addons:
  artifacts: true
  s3_region: Oregon
